### ISSUE TITLE
AttributeError: 'ellipsis' object has no attribute 'encode'

### ISSUE THREAD

**Issue by drummerjun** [TomaszGolan/hdf5_manipulator#2] opened 2020-04-16 08:47 UTC
I keep running into this error, both on Python 2 & 3...
Is there anything wrong with how I execute the function(s)?

Traceback (most recent call last):
  File "/hdf5_manipulator-master/merge.py", line 77, in <module>
    data[f] = hdf5.load(f)
  File "/hdf5_manipulator-master/hdf5.py", line 22, in load
    data[key] = f[key][...]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/hdf5_manipulator-master/venv/lib/python2.7/site-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "/hdf5_manipulator-master/venv/lib/python2.7/site-packages/h5py/_hl/base.py", line 137, in _e
    name = name.encode('ascii')
AttributeError: 'ellipsis' object has no attribute 'encode'

**Comment by gnperdue** [comment] 2020-04-16 15:25
It's been a pretty long time since I looked at this code. I did make a fork and change a few things

https://github.com/gnperdue/hdf5_manipulator

but nothing in `merge.py`. Maybe you'll see something interesting there though... Can you provide the smallest possible reproduction of the error? Also, looking at the stacktrace, the problem could be in h5py. What version of h5py are you using? It is possible the API has evolved in the several years since we touched this code.

**Comment by drummerjun** [comment] 2020-04-17 08:05
Ya I realized this has not been maintained for a while, but due to lack of h5 merging/combining tools online, thought I'd give a shot...

my Pycharm is using h5py v2.10

and JIC, the error occurred in load() in hdf5.py:
    for key in f:
        data[key] = f[key][...]

**Comment by gnperdue** [comment] 2020-07-08 17:17
@drummerjun - I have no idea if you found a workaround or gave up on this, but I wanted to point out that I migrated the code to Python 3 over in 

https://github.com/gnperdue/hdf5_manipulator

I have a pull request - #3 - open for this although I don't know if Tomek will see it. Whatever the case, you might try that code and see if it helps...

**Comment by BRCH5** [comment] 2021-08-18 16:33
Hi there,

I am getting a similar error message to the issue above:
_'TypeError: Accessing a group is done with bytes or str,  not <class 'ellipsis'>'_
The error also occurs in the same spot of the hdf5.py file
_for key in f:
data[key] = f[key][...]_

Do you have any recommendations as to how I might solve this issue?

Thank you :)

**Comment by gnperdue** [comment] 2021-08-18 17:44
@BRCH5 did you try the Python3 version I linked above? If so, can you provide (maybe in a gist) a minimal example that reproduces the error? I only look at this code about once every few years since I don't need it much and my personal use cases are all ironed out, ha.

**Comment by BRCH5** [comment] 2021-08-19 07:50
@gnperdue Thank you for your speedy response!

Yes I tried the Python3 version as above. The merge.py script is locating my .h5 files but trips at line 79 when it calls hdf5.load().
I've pasted a snippet version of what I am seeing below.

merge.py --input  PathToFile1\File1.h5,PathToFile2\File2.h5 --output merged.hdf5

[94m
+--------------------------------------------------------------------------------+
|                                                                                |
|                            HDF5 MANIPULATOR: MERGE                             |
|                                                                                |
+--------------------------------------------------------------------------------+
[0m
The following input files were found:

         - PathToFile1\File1.h5
         - PathToFile2\File2.h5
Traceback (most recent call last):
  File "C:\...\hdf5_manipulator\merge.py", line 79, in <module>
    data[f] = hdf5.load(f)
  File "C:\...\hdf5_manipulator\hdf5.py", line 21, in load
    data[key] = f[key][...]
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\Anaconda3\...\lib\site-packages\h5py\_hl\group.py", line 307, in __getitem__
    raise TypeError("Accessing a group is done with bytes or str, "
TypeError: Accessing a group is done with bytes or str,  not <class 'ellipsis'>

**Comment by gnperdue** [comment] 2021-08-21 00:02
@BRCH5 Is it possible to make a tiny sample HDF5 file that reproduces the error that I could try? Because it works for me and I wonder if you have a corrupted HDF5 file. Or, maybe better, check out

https://github.com/gnperdue/RandomData/tree/master/hdf5

I have some scripts that make an HDF5 file from the Keras version of FashionMNIST (`make_fasion_mnist_hdf5.py`). I haven't run those scripts in a while so they may need a tweak to work. But anyway, you should be able to merge the train and test sets. If that fails for you, show me those errors.

**Comment by BRCH5** [comment] 2021-08-23 14:33
@gnperdue Thank you for your last suggestion! I was able to merge the train and test sets from the link you mentioned above, so there must be something wrong with my HDF5 files. Github does not support the .hdf5 extension in these comment boxes so I have uploaded samples of my HDF5 file onto a repo and shared the repo with you.
I really appreciate your help to-date, even now I know my HDF5 must be corrupted it is something I can debug further myself. 
Thanks :)

**Comment by gnperdue** [comment] 2021-08-26 17:43
Okay, great, glad to help. How are you making your HDF5 files? `h5py` is a great package with good documentation, and I've used it a lot in the past. It is missing some utilities (like merge, obviously, haha), but it is a good utility for making hdf5s.

**Closed as completed by gnperdue** 2021-08-26 17:43 UTC
